package com.caiyu.hearthstone.model.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "card".
 */
public class CardEntity {

    private long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String color;
    private int cost;
    /** Not-null value. */
    private String job;
    /** Not-null value. */
    private String type;
    private Integer attack;
    private Integer blood;
    private String description;

    public CardEntity() {
    }

    public CardEntity(long id) {
        this.id = id;
    }

    public CardEntity(long id, String name, String color, int cost, String job, String type, Integer attack, Integer blood, String description) {
        this.id = id;
        this.name = name;
        this.color = color;
        this.cost = cost;
        this.job = job;
        this.type = type;
        this.attack = attack;
        this.blood = blood;
        this.description = description;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getColor() {
        return color;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setColor(String color) {
        this.color = color;
    }

    public int getCost() {
        return cost;
    }

    public void setCost(int cost) {
        this.cost = cost;
    }

    /** Not-null value. */
    public String getJob() {
        return job;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setJob(String job) {
        this.job = job;
    }

    /** Not-null value. */
    public String getType() {
        return type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setType(String type) {
        this.type = type;
    }

    public Integer getAttack() {
        return attack;
    }

    public void setAttack(Integer attack) {
        this.attack = attack;
    }

    public Integer getBlood() {
        return blood;
    }

    public void setBlood(Integer blood) {
        this.blood = blood;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
